### ISSUE TITLE
Crash when entering Inv Core GUI

### ISSUE THREAD

**Issue by Fortist** [MCTechnicGuy/AdvancedInventoryManagement#1]
Placed the block, opened the GUI and went to scroll over something and then it crashed.
Latest version, highest forge.
```
> ---- Minecraft Crash Report ----
> // Hi. I'm Minecraft, and I'm a crashaholic.
> 
> Time: 2018-07-27 12:42:19 EDT
> Description: Rendering screen
> 
> java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
>     at com.mctechnicguy.aim.gui.GuiAIMCore.drawGuiContainerForegroundLayer(GuiAIMCore.java:91)
>     at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:117)
>     at com.mctechnicguy.aim.gui.GuiAIMCore.drawScreen(GuiAIMCore.java:40)
>     at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
>     at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
>     at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117)
>     at net.minecraft.client.Minecraft.run(Minecraft.java:3938)
>     at net.minecraft.client.main.Main.main(SourceFile:123)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
>     at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
>     at org.multimc.EntryPoint.listen(EntryPoint.java:143)
>     at org.multimc.EntryPoint.main(EntryPoint.java:34)
> Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
>     at java.net.URLClassLoader.findClass(Unknown Source)
>     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     ... 22 more
```

**Comment by MCTechnicGuy** [comment]
Thanks for the notification, the problem should be fixed in the next version!
