### ISSUE TITLE
Crash after installing OptiFine_HD_U_E2

### ISSUE THREAD

**Issue by skyinr** [MCTechnicGuy/AdvancedInventoryManagement#2]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 8/2/18 11:31 AM
Description: Initializing game

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: net.minecraft.client.renderer.block.model.ItemOverrideList.getOverrides()Lcom/google/common/collect/ImmutableList;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:424)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.renderer.block.model.ItemOverrideList.getOverrides()Lcom/google/common/collect/ImmutableList;
	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.<init>(AnimationItemOverrideList.java:53)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1.<init>(ModelLoader.java:494)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bakeNormal(ModelLoader.java:492)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bakeImpl(ModelLoader.java:454)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:821)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:817)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:424)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 166950328 bytes (159 MB) / 419430400 bytes (400 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2745 Optifine OptiFine_1.12.2_HD_U_E2_pre 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                                       | Signature                                |
	|:----- |:--------- |:------------ |:-------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft | 1.12.2       | minecraft.jar                                | None                                     |
	| UCH   | mcp       | 9.42         | minecraft.jar                                | None                                     |
	| UCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.4.2745.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge     | 14.23.4.2745 | forge-1.12.2-14.23.4.2745.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | aim       | 1.4.0        | AdvancedInventoryManagement-1.12.2-1.4.0.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 315/PCI/SSE2/3DNOW!'
	Launched Version: HMCL 3.1.64
	LWJGL: 2.9.4
	OpenGL: GeForce 315/PCI/SSE2/3DNOW! GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD Athlon(tm) 64 X2 Dual Core Processor 3800+
	OptiFine Version: OptiFine_1.12.2_HD_U_E2_pre
	OptiFine Build: 20180705-160641
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0
	OpenGlRenderer: GeForce 315/PCI/SSE2/3DNOW!
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by MCTechnicGuy** [comment]
I tried to reproduce your error but was able to load up the game with the same configuration as yours just fine. Please try updating to the newest versions of AIM and Forge.

**Comment by skyinr** [comment]
Thank you very much for it.
